name: 'cmsch-pass-generator'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7070:3000'
    env_file:
      - .env
    volumes:
      - ./templates:/usr/src/app/templates
      - ./creds:/usr/src/app/creds
